version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4

aliases:
  - &restore-cache
    restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
  - &save-cache
    save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
  - &install-deps
    run:
        name: Install dependencies
        command: npm ci
  - &lerna-bootstrap
    run:
        name: Lerna bootstrap
        command: npm run bootstrap
  - &build-packages
    run:
        name: Build
        command: npm run build
  - &run-unit-tests
    run:
        name: Test
        command: npm run test
  - &run-lint
    run:
        name: Lint
        command: npm run lint

unit-tests-template: &unit-tests-template
  working_directory: ~/fluentfixture
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *lerna-bootstrap
    - *build-packages
    - *run-unit-tests

jobs:
  build:
    working_directory: ~/fluentfixture
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *save-cache
      - *install-deps
      - *lerna-bootstrap
      - *build-packages

  test_node_10:
    docker:
      - image: circleci/node:10
    <<: *unit-tests-template

  test_node_12:
    docker:
      - image: circleci/node:12
    <<: *unit-tests-template

  test_node_14:
    docker:
      - image: circleci/node:14
    <<: *unit-tests-template

  test_node_16:
    docker:
      - image: circleci/node:16
    <<: *unit-tests-template

  coverage:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *lerna-bootstrap
      - *build-packages
      - *run-unit-tests
      - coveralls/upload

  lint:
    working_directory: ~/fluentfixture
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *lerna-bootstrap
      - *run-lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test_node_10:
          requires:
            - build
      - test_node_12:
          requires:
            - build
      - test_node_14:
          requires:
            - build
      - test_node_16:
          requires:
            - build
      - lint:
          requires:
            - build
      - coverage:
          requires:
            - test_node_10
            - test_node_12
            - test_node_14
            - test_node_16
