version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0
  coveralls: coveralls/coveralls@2.1.0
  commitlint: conventional-changelog/commitlint@1.0.0

aliases:
  - &install-deps
    run:
      name: Install Dependencies
      command: HUSKY_DISABLED=1 npm ci
  - &lerna-bootstrap
    run:
      name: Lerna Bootstrap
      command: npm run bootstrap
  - &build-packages
    run:
      name: Build Packages
      command: npm run build
  - &run-unit-tests
    run:
      name: Unit Tests
      command: npm run test
  - &run-lint
    run:
      name: Linters
      command: npm run lint
  - &run-depcruise
    run:
      name: Depencency Checks
      command: npm run depcruise

build-template: &build-template
  working_directory: ~/fluentfixture
  steps:
    - checkout
    - *install-deps
    - *lerna-bootstrap
    - *build-packages
    - *run-unit-tests

jobs:
  test_node_12:
    docker:
      - image: cimg/node:12.22
    <<: *build-template

  test_node_14:
    docker:
      - image: cimg/node:14.21
    <<: *build-template

  test_node_16:
    docker:
      - image: cimg/node:16.18
    <<: *build-template

  test_node_18:
    docker:
      - image: cimg/node:18.20.4
    <<: *build-template

  security:
    working_directory: ~/fluentfixture
    docker:
      - image: cimg/node:18.20.4
    steps:
      - checkout
      - *install-deps
      - *lerna-bootstrap
      - snyk/scan:
          additional-arguments: --all-projects --strict-out-of-sync=false

  quality:
    working_directory: ~/fluentfixture
    docker:
      - image: cimg/node:18.20.4
    steps:
      - checkout
      - *install-deps
      - *lerna-bootstrap
      - *build-packages
      - *run-lint
      - *run-depcruise
      - *run-unit-tests
      - coveralls/upload

workflows:
  version: 2
  build-and-test:
    jobs:
      - commitlint/lint:
          max-count: 2
          node-version: "18.20.4"
      - security:
          requires:
            - commitlint/lint
      - test_node_16:
          requires:
            - security
      - test_node_18:
          requires:
            - security
      - quality:
          requires:
            - test_node_16
            - test_node_18
