import { spy, verify, when } from 'ts-mockito';
import { Random } from '../../../src/engine/random';
import { MockFactory } from '../../mocks/mock-factory';
import { NON_INTEGER_DATA_SET } from '../../data/type-sets';
import { MAX_ARRAY_SIZE, MIN_ARRAY_SIZE } from '../../../src/constants/limits';
import { Sampler } from '../../../src/factories/decorators/sampler';

describe('Sampler', () => {

  describe('.constructor()', () => {

    describe('parameter assertions (size)', () => {

      test.each(NON_INTEGER_DATA_SET)('should throw an error when size is not an integer, given: %s', (size: any) => {

        const thrown = () => new Sampler(new MockFactory([]), size);

        expect(thrown).toThrow('[Sampler.constructor(factory, size)].[size]: Parameter must be an integer!');
      });

      it('should throw an error when size is less than the minimum array length', () => {

        const thrown = () => new Sampler(new MockFactory([]), MIN_ARRAY_SIZE - 1);

        expect(thrown).toThrow(`[Sampler.constructor(factory, size)].[size]: Parameter must be between ${MIN_ARRAY_SIZE} and ${MAX_ARRAY_SIZE}!`);
      });

      it('should throw an error when size is greater than the maximum array length', () => {

        const thrown = () => new Sampler(new MockFactory([]), MAX_ARRAY_SIZE + 1);

        expect(thrown).toThrow(`[Sampler.constructor(factory, size)].[size]: Parameter must be between ${MIN_ARRAY_SIZE} and ${MAX_ARRAY_SIZE}!`);
      });
    });
  });

  describe('.single()', () => {

    it('should takes values from the array which generated by the given factory', () => {
      const spyEngine = spy(Random);
      const size = 2;
      const arr = [1, 2, 3];
      const out = [1, 2];
      const factory = new Sampler(new MockFactory(arr), size);

      when(spyEngine.sample(arr, size)).thenReturn(out);

      const result = factory.single();

      expect(result).toBe(out);
      verify(spyEngine.sample(arr, size)).once();
    });
  });
});
