import { spy, verify, when } from 'ts-mockito';
import { Random } from '../../../src/engine/random';
import { MockFactory } from '../../mocks/mock-factory';
import { Shuffler } from '../../../src/factories/decorators/shuffler';

describe('Shuffler', () => {

  describe('.single()', () => {

    it('should shuffles the array which generated by the given factory', () => {
      const spyEngine = spy(Random);
      const arr = [1, 2, 3];
      const out = [1, 3, 2];
      const factory = new Shuffler(new MockFactory(arr));

      when(spyEngine.shuffle(arr)).thenReturn(out);

      const result = factory.single();

      expect(result).toBe(out);
      verify(spyEngine.shuffle(arr)).once();
    });
  });
});
